name: dartivity_database
version: 1.0.0
author: Steve Hamblett<steve.hamblett@linux.com>
description: The database component of the Dartivity IOT suite of packages.
homepage: https://github.com/shamblett/dartivity_database
environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'
dependencies:
  wilt: '^5.0.0'
  json_object_lite: '^2.1.1'
  crypto: '>=2.0.1 <3.0.0'

dev_dependencies:
  test: '^1.16.0-nullsafety.16'
  pana: '^0.14.10'
  build_runner: '^1.10.3'
  build_test: '^1.3.4'
  build_web_compilers: '^2.16.0'

